# Generated by Django 5.1 on 2025-08-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraiser_owner_pledge_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='location',
            field=models.CharField(choices=[('australia', 'Australia'), ('newzealand', 'New Zealand'), ('canada', 'Canada'), ('japan', 'Japan')], default='australia', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundraiser',
            name='media',
            field=models.CharField(choices=[('tv', 'Television'), ('film', 'Film,')], default='tv', max_length=20),
            preserve_default=False,
        ),
    ]
