# Generated by Django 5.1 on 2025-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_fundraiser_location_fundraiser_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='media',
            field=models.CharField(choices=[('tv', 'Television'), ('film', 'Film')], max_length=20),
        ),
    ]
